-- Run in Supabase SQL Editor (or via CLI) once per project.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  phone text not null default '',
  weekly_classes int not null default 1,
  plan_value numeric(10, 2) not null default 0,
  color text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  student_id bigint not null references public.students (id) on delete cascade,
  day text not null check (day in ('seg', 'ter', 'qua', 'qui', 'sex', 'sab', 'dom')),
  time text not null,
  duration_minutes int not null default 45,
  created_at timestamptz not null default now(),
  unique (student_id, day, time)
);

create index if not exists sessions_day_idx on public.sessions (day);
create index if not exists sessions_student_id_idx on public.sessions (student_id);

-- Banco que já existia antes de user_id: a create table acima não altera a tabela.
alter table public.students
  add column if not exists user_id uuid references auth.users (id) on delete cascade;
alter table public.sessions
  add column if not exists user_id uuid references auth.users (id) on delete cascade;

create index if not exists students_user_id_idx on public.students (user_id);
create index if not exists sessions_user_id_idx on public.sessions (user_id);

-- Troque pelo e-mail da conta que já usa esta agenda. Sem isso, linhas antigas
-- ficam sem dono e o set not null abaixo falha.
update public.students
set user_id = (select id from auth.users where email = 'personaltrainerjean@gmail.com')
where user_id is null
  and exists (select 1 from auth.users where email = 'personaltrainerjean@gmail.com');

update public.sessions as s
set user_id = st.user_id
from public.students as st
where s.student_id = st.id
  and s.user_id is null
  and st.user_id is not null;

alter table public.students alter column user_id set not null;
alter table public.sessions alter column user_id set not null;

-- A API usa a secret key, que ignora RLS. A policy trava a chave anônima.
alter table public.students enable row level security;
alter table public.sessions enable row level security;

drop policy if exists students_own on public.students;
create policy students_own on public.students
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists sessions_own on public.sessions;
create policy sessions_own on public.sessions
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.professor_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  whatsapp_phone text not null default '',
  last_summary_on date
);

alter table public.professor_settings enable row level security;

drop policy if exists professor_settings_own on public.professor_settings;
create policy professor_settings_own on public.professor_settings
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Estatísticas: situação do aluno, tabela vigente e pagamentos do mês.
alter table public.students
  add column if not exists status text not null default 'ativo';
alter table public.students
  add column if not exists started_on date;
alter table public.students
  add column if not exists ended_on date;
alter table public.students
  add column if not exists billing_day integer;
alter table public.students
  add column if not exists custom_price boolean not null default false;

alter table public.students drop constraint if exists students_status_check;
alter table public.students
  add constraint students_status_check
  check (status in ('ativo', 'pausado', 'encerrado'));

alter table public.students drop constraint if exists students_billing_day_check;
alter table public.students
  add constraint students_billing_day_check
  check (billing_day is null or (billing_day >= 1 and billing_day <= 28));

create table if not exists public.plan_prices (
  user_id uuid not null references auth.users (id) on delete cascade,
  weekly_classes int not null check (weekly_classes between 1 and 7),
  amount numeric(10, 2) not null check (amount >= 0),
  primary key (user_id, weekly_classes)
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  student_id bigint not null references public.students (id) on delete cascade,
  competence date not null,
  amount numeric(10, 2) not null check (amount >= 0),
  due_on date,
  paid_on date,
  unique (student_id, competence)
);

create index if not exists payments_user_competence_idx
  on public.payments (user_id, competence);

alter table public.plan_prices enable row level security;
alter table public.payments enable row level security;

drop policy if exists plan_prices_own on public.plan_prices;
create policy plan_prices_own on public.plan_prices
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists payments_own on public.payments;
create policy payments_own on public.payments
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
