-- Run in Supabase SQL Editor (or via CLI) once per project.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  weekly_classes int not null default 1,
  plan_value numeric(10, 2) not null default 0,
  color text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  day text not null check (day in ('seg', 'ter', 'qua', 'qui', 'sex', 'sab', 'dom')),
  time text not null,
  duration_minutes int not null default 45,
  created_at timestamptz not null default now(),
  unique (student_id, day, time)
);

create index if not exists sessions_day_idx on public.sessions (day);
create index if not exists sessions_student_id_idx on public.sessions (student_id);

-- Personal app: service role on the Express server bypasses RLS.
-- Keep RLS off for simplicity (or enable with no anon policies).
alter table public.students enable row level security;
alter table public.sessions enable row level security;
