-- Run in Supabase SQL Editor (or via CLI) once per project.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  phone text not null default '',
  weekly_classes int not null default 1,
  plan_value numeric(10, 2) not null default 0,
  color text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  student_id bigint not null references public.students (id) on delete cascade,
  day text not null check (day in ('seg', 'ter', 'qua', 'qui', 'sex', 'sab', 'dom')),
  time text not null,
  duration_minutes int not null default 45,
  created_at timestamptz not null default now(),
  unique (student_id, day, time)
);

create index if not exists sessions_day_idx on public.sessions (day);
create index if not exists sessions_student_id_idx on public.sessions (student_id);

-- Banco que já existia antes de user_id: a create table acima não altera a tabela.
alter table public.students
  add column if not exists user_id uuid references auth.users (id) on delete cascade;
alter table public.sessions
  add column if not exists user_id uuid references auth.users (id) on delete cascade;

create index if not exists students_user_id_idx on public.students (user_id);
create index if not exists sessions_user_id_idx on public.sessions (user_id);

-- Troque pelo e-mail da conta que já usa esta agenda. Sem isso, linhas antigas
-- ficam sem dono e o set not null abaixo falha.
update public.students
set user_id = (select id from auth.users where email = 'personaltrainerjean@gmail.com')
where user_id is null
  and exists (select 1 from auth.users where email = 'personaltrainerjean@gmail.com');

update public.sessions as s
set user_id = st.user_id
from public.students as st
where s.student_id = st.id
  and s.user_id is null
  and st.user_id is not null;

alter table public.students alter column user_id set not null;
alter table public.sessions alter column user_id set not null;

-- A API usa a secret key, que ignora RLS. A policy trava a chave anônima.
alter table public.students enable row level security;
alter table public.sessions enable row level security;

drop policy if exists students_own on public.students;
create policy students_own on public.students
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists sessions_own on public.sessions;
create policy sessions_own on public.sessions
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
